
## Access the Soundcloud API

soundR is an R-package which provides access to the Soundcloud API. The packages supports all API calls that are useful for data mining and analysis. Further API calls will be added in the future. For an overview of possible API calls see <https://developers.soundcloud.com/docs/api/reference>. All data from Soudncloud will be returned in user friendly data frames.

## How to install the package

- First you have to create a Soundcloud application at <https://developers.soundcloud.com/>. Click on "Register a new app".
- If you have a registered app, please note down the "client ID" that can be found at <https://soundcloud.com/you/apps>.
- To install the Github version of the package:
  - Install devtools `if(!require("devtools")) install.packages("devtools")`
  - Start a new session, load devtools, and install soundR from Github.
  - `library(devtools)`
  - `install_github("adrauc/soundR")`
- Now you can load the library:
  - `library(soundR)`
- That's it, you can now use the functions in the package.

## How to use the package

To make API calls, you need to add your "client ID" to most functions.
Usually you first need the user ID of a user. You can get the user ID of a user with the function `get_user()`. Then you can use other functions such as `get_tracks()`.
```{r}
# first add your client ID
client_id <- "Your_Client_ID"
# first define the user name 
# the user name is the last part of a user page URL
# e.g. https://soundcloud.com/joshuakatharsis
username <- "joshuakatharsis"
# now search for this user
user_df <- get_user(username, client_id)
# now you have the user ID of this user in
user_df$id
# now we can use other functions and get information about all tracks of this user
user_id <- user_df$id
tracks_id <- get_tracks(user_id, client_id)
tracks_id
```


```
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
```
